name: "Pull Request"
description: Open a Pull Request
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to open this pull request! **Before you start, make sure you have the latest versions of the packages you're using**
  - type: textarea
    id: description
    attributes:
      label: Describe the changes made in this PR
      placeholder: Adds
    validations:
      required: true
  - type: checkboxes
    id: what-changed
    attributes:
      label: Which packages/starters are effected?
      description: Check all that apply
      options:
        - label: next-drupal
        - label: gatsby-wordpress
        - label: drupal-kit
        - label: wordpress-kit
        - label: documentation
        - label: monorepo
        - label: new package or starter
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Information
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description:
        The Code of Conduct helps create a safe space for everyone. We require
        that everyone agrees to it.
      options:
        - label: I agree to follow this project's [Code of Conduct](https://github.com/pantheon-systems/decoupled-kit-js/blob/canary/CODE_OF_CONDUCT.md)
          required: true
  - type: markdown
    attributes:
      value: Don't forget to [add a changeset](https://github.com/pantheon-systems/decoupled-kit-js#generating-a-changeset) if needed!
